//! `wmux completion powershell`: a completer for the shell, printed as a
//! script to dot-source (`wmux completion powershell | Out-String |
//! Invoke-Expression` in `$PROFILE`). PowerShell completes only what it is
//! told about, and a native program is told through
//! `Register-ArgumentCompleter`; the script carries the command names and
//! each command's flags out of the parser's own tables, and asks the
//! running server for session and window names after `-t`.

use anyhow::{Result, bail};

/// Commands the client handles itself, which `list-commands` does not show.
const LOCAL: &[&str] = &["completion", "restart-server", "show-keys", "startup", "update", "web", "windows-terminal"];

/// Values `completion` takes: the shells there is a script for.
const SHELLS: &[&str] = &["powershell"];

/// The PowerShell completer, ready to `Invoke-Expression`.
pub fn powershell() -> String {
    let mut commands: Vec<&str> = crate::command::COMMANDS.iter().copied().chain(LOCAL.iter().copied()).collect();
    commands.sort_unstable();
    let command_list = commands.iter().map(|c| format!("'{c}'")).collect::<Vec<_>>().join(",");
    let flag_table = crate::command::FLAGS
        .iter()
        .filter(|(_, f)| !f.is_empty())
        .map(|(c, f)| format!("  '{c}' = @({})", f.iter().map(|x| format!("'{x}'")).collect::<Vec<_>>().join(",")))
        .collect::<Vec<_>>()
        .join("\n");
    let quoted = |items: &[&str]| items.iter().map(|x| format!("'{x}'")).collect::<Vec<_>>().join(",");
    // PowerShell hashtables ignore case, so only one of `-V` / `-v` style
    // pairs could be a key; the aliases have none.
    let alias_table = crate::command::ALIASES
        .iter()
        .filter(|(a, _)| !a.starts_with('-'))
        .map(|(a, c)| format!("  '{a}' = '{c}'"))
        .collect::<Vec<_>>()
        .join("\n");
    let option_list = quoted(crate::config::KNOWN);
    let value_table = crate::config::KNOWN
        .iter()
        .filter(|o| !crate::config::option_values(o).is_empty())
        .map(|o| format!("  '{o}' = @({})", quoted(crate::config::option_values(o))))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#"# wmux completion for PowerShell. Generated by `wmux completion powershell`.
# Completes command names, each command's flags, `-t` targets from the
# running server, option names and values after `set` / `show`, and the
# values of `-L` (sockets) and `completion`. Registered for `tmux` too, for
# those who alias it to wmux.
Register-ArgumentCompleter -Native -CommandName wmux,tmux -ScriptBlock {{
  param($wordToComplete, $commandAst, $cursorPosition)
  $commands = @({command_list})
  $flags = @{{
{flag_table}
  }}
  $options = @({option_list})
  $values = @{{
{value_table}
  }}
  $aliases = @{{
{alias_table}
  }}
  $words = @($commandAst.CommandElements | ForEach-Object {{ $_.Extent.Text }})
  # The words before the cursor, the program's own name dropped.
  $before = @($words | Select-Object -Skip 1)
  $typing = $wordToComplete -ne ''
  if ($typing -and $before.Count -gt 0) {{ $before = @($before | Select-Object -SkipLast 1) }}
  # Global flags come first: -L socket, -f config, -q.
  $socket = 'default'
  $i = 0
  while ($i -lt $before.Count -and $before[$i] -like '-*') {{
    if ($before[$i] -eq '-L' -and $i + 1 -lt $before.Count) {{ $socket = $before[$i + 1]; $i += 2 }}
    elseif ($before[$i] -eq '-f' -and $i + 1 -lt $before.Count) {{ $i += 2 }}
    else {{ $i += 1 }}
  }}
  $rest = @($before | Select-Object -Skip $i)
  $prev = if ($before.Count -gt 0) {{ $before[-1] }} else {{ '' }}
  # The command as the server reads it: an alias (`splitw`, `set`) or an
  # unambiguous prefix (`split-w`) stands for its full name.
  $canon = ''
  if ($rest.Count -gt 0) {{
    $canon = $rest[0]
    if (-not $aliases.ContainsKey($canon) -and $commands -notcontains $canon) {{
      $hits = @($commands | Where-Object {{ $_ -like "$canon*" }})
      if ($hits.Count -eq 1) {{ $canon = $hits[0] }}
    }}
    if ($aliases.ContainsKey($canon)) {{ $canon = $aliases[$canon] }}
  }}
  $out = @()
  if ($rest.Count -eq 0) {{
    if ($prev -eq '-L') {{
      # Sockets: the named pipes of running servers.
      $out = Get-ChildItem '\\.\pipe\' -ErrorAction SilentlyContinue | ForEach-Object {{ $_.Name }} |
        Where-Object {{ $_ -match '^wmux-[^-]+-(.+)$' }} | ForEach-Object {{ $Matches[1] }} | Sort-Object -Unique
    }} else {{
      $out = $commands
    }}
  }} elseif ($rest[0] -eq 'completion') {{
    $out = @('powershell')
  }} elseif ($canon -in @('set-option','show-options') -and $prev -ne '-t' -and $wordToComplete -notlike '-*') {{
    # After set / show: the option's name, then its value when it is one
    # of a few. Flags are skipped, and so is the word after -t.
    $positional = @()
    for ($j = 1; $j -lt $rest.Count; $j++) {{
      if ($rest[$j] -eq '-t') {{ $j++ }} elseif ($rest[$j] -notlike '-*') {{ $positional += $rest[$j] }}
    }}
    if ($positional.Count -eq 0) {{ $out = $options }}
    elseif ($positional.Count -eq 1 -and $values.ContainsKey($positional[0])) {{ $out = $values[$positional[0]] }}
  }} elseif ($prev -eq '-t' -or $prev -eq '-s') {{
    # Targets: session names and session:window from the server.
    $sessions = & wmux -L $socket list-sessions 2>$null | ForEach-Object {{ if ($_ -match '^([^:]+):') {{ $Matches[1] }} }}
    $out = @($sessions)
    foreach ($s in $sessions) {{
      $out += & wmux -L $socket list-windows -t $s 2>$null | ForEach-Object {{ if ($_ -match '^(\d+): (\S+?)[*-]? ') {{ "${{s}}:$($Matches[1])"; "${{s}}:$($Matches[2])" }} }}
    }}
  }} elseif ($wordToComplete -like '-*') {{
    # Flags only when one is being typed: after a flag that takes a value
    # (or a positional), nothing is known to offer.
    $out = $flags[$canon]
  }}
  $out | Where-Object {{ $_ -like "$wordToComplete*" }} | ForEach-Object {{
    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
  }}
}}
"#
    )
}

/// `wmux completion <shell>`: print the completer for that shell.
pub fn run(args: &[String]) -> Result<i32> {
    match args {
        [shell] if shell == "powershell" || shell == "pwsh" => {
            print!("{}", powershell());
            Ok(0)
        }
        [shell] => bail!("completion: no script for '{shell}' (one of {})", SHELLS.join(", ")),
        [] => bail!("completion: which shell? (one of {})", SHELLS.join(", ")),
        _ => bail!("completion: one shell name, nothing else"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The script carries what the parser knows: every command, every
    /// flagged command's flags, and nothing that would break a here-string.
    #[test]
    fn the_script_lists_every_command_and_flag() {
        let s = powershell();
        assert!(s.starts_with("# wmux completion"));
        assert!(s.contains("Register-ArgumentCompleter -Native -CommandName wmux"));
        for c in crate::command::COMMANDS.iter().chain(LOCAL) {
            assert!(s.contains(&format!("'{c}'")), "{c} is not offered");
        }
        for (c, flags) in crate::command::FLAGS {
            if flags.is_empty() {
                continue;
            }
            let line =
                s.lines().find(|l| l.trim_start().starts_with(&format!("'{c}' = @("))).unwrap_or_else(|| panic!("{c}"));
            for f in *flags {
                assert!(line.contains(&format!("'{f}'")), "{c} lacks {f}: {line}");
            }
        }
        // Balanced: what Invoke-Expression needs before anything else.
        assert_eq!(s.matches('{').count(), s.matches('}').count(), "braces");
        assert_eq!(s.matches('(').count(), s.matches(')').count(), "parens");
    }

    #[test]
    fn only_shells_with_a_script_are_taken() {
        assert_eq!(run(&["powershell".into()]).unwrap(), 0);
        assert_eq!(run(&["pwsh".into()]).unwrap(), 0);
        assert!(run(&["bash".into()]).unwrap_err().to_string().contains("no script for 'bash'"));
        assert!(run(&[]).unwrap_err().to_string().contains("which shell"));
        assert!(run(&["a".into(), "b".into()]).is_err());
    }
}
