//! keepane: a terminal multiplexer whose panes keep running and pass messages to each other.

pub mod client;
pub mod clipboard;
pub mod command;
pub mod completion;
pub mod config;
pub mod console;
pub mod dashboard;
pub mod format;
pub mod histlog;
pub mod ipc;
pub mod keys;
pub mod legacy;
pub mod logger;
pub mod mcp;
pub mod notify;
pub mod pager;
pub mod proccwd;
pub mod resurrect;
pub mod server;
pub mod setup;
pub mod shutdown;
pub mod startup;
pub mod sysinfo;
pub mod update;
pub mod web;
pub mod winsec;
pub mod wt;
